### ISSUE TITLE
Problem with pymobiledevice3

### ISSUE THREAD

**Issue by Zyzzyva0381** [BiancoChiu/iOSRealRun-cli-18#2]
I am working with Python 3.13.2 and Windows 11, installing the requirements via `requirements.txt` in a venv environment. 

When running

```
python main.py
```

The following exception occurred. 

```
Your system version is 18.3.1
Traceback (most recent call last):
  File "D:\programs\test\iOSRealRun-cli-18\main.py", line 83, in <module>
    asyncio.run(main())
  File "D:\Program_Files\anaconda3\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "D:\Program_Files\anaconda3\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program_Files\anaconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\programs\test\iOSRealRun-cli-18\main.py", line 43, in main
    init.init()
  File "D:\programs\test\iOSRealRun-cli-18\init\init.py", line 34, in init
    connect.reveal_developer_mode(lockdown)
  File "D:\programs\test\iOSRealRun-cli-18\driver\connect.py", line 39, in reveal_developer_mode
    AmfiService(lockdown).create_amfi_show_override_path_file()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AmfiService' object has no attribute 'create_amfi_show_override_path_file'
```

**Comment by BiancoChiu** [comment]
Hi. This error occurs because Developer Mode is not enabled on your device. In the previous version of `iOSRealRun-cli-17`, which relies on an older version of `pymobiledevice3`, the tool was designed to prompt you to check the Developer Mode status. 
```    
if not developer_mode_status:
        connect.reveal_developer_mode(lockdown)
        print("您未开启开发者模式，请打开设备的 设置-隐私与安全性-开发者模式 来开启，开启后需要重启并输入密码，完成后再次运行此程序")
        sys.exit(1)
```
However, due to changes in a method within `AmfiService`, the error is no longer being raised correctly. I will address this issue in a future update.

Please ensure that Developer Mode is enabled on your device and try running the tool again. Let me know if there is any other issue.
